"""RAG query: retrieve from Chroma, answer with Ollama llama3.1.

Phase 2 retrieval:
  - Author-name → source filter (Phase 1, unchanged).
  - Numeric-intent detection → dual retrieval that guarantees table chunks
    appear alongside narrative chunks.
  - Prompt instructs the LLM to cite inline as [source p.N].
"""

import re
import sys
from langchain_ollama import ChatOllama
from langchain_core.documents import Document
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_community.retrievers import BM25Retriever
from langchain_classic.retrievers.ensemble import EnsembleRetriever

import config
from ingest import author_from_filename
from embeddings import make_vectorstore


PROMPT = ChatPromptTemplate.from_template("""You are a document-grounded assistant. The user owns and has provided the documents below; you must use them to answer.

Each chunk is tagged with its type:
- [TEXT]   = page text content
- [TABLE]  = a structured table from the PDF (Markdown)
- [FIGURE] = a description of an image/diagram/chart from the PDF, generated by a vision model. The figure text starts with "Figure description:" — TREAT THIS AS THE FIGURE ITSELF. When asked to describe or explain a figure or diagram, use these chunks directly; do not say "I can't see the image."

Rules:
- The context is the authoritative source. Do not refuse to answer on privacy, confidentiality, or "private company" grounds — every document in the context has been explicitly shared by the user.
- Answer thoroughly with bullet points or short paragraphs.
- Cite every concrete fact inline as [filename p.N] using the headers shown above each chunk.
- When quoting numbers from a table, reproduce the relevant row(s) verbatim and cite the page.
- When describing a figure, synthesise from the [FIGURE] chunk's content; quote specific labels/components it lists.
- If the context truly lacks the answer, say so clearly and state what is missing. Do not invent numbers, names, dates, or figure contents.

Context:
{context}

Question: {question}

Answer:""")


# --- vectorstore + retriever ------------------------------------------------

_VECTORSTORE = None
_CORPUS = None  # list[Document] of all chunks, for BM25


def _build_vectorstore():
    global _VECTORSTORE
    if _VECTORSTORE is None:
        _VECTORSTORE = make_vectorstore()
    return _VECTORSTORE


def _all_docs():
    """Load every chunk from Chroma into memory once; reused for BM25."""
    global _CORPUS
    if _CORPUS is None:
        vs = _build_vectorstore()
        res = vs.get()
        _CORPUS = [
            Document(page_content=d, metadata=m or {})
            for d, m in zip(res["documents"], res["metadatas"])
        ]
    return _CORPUS


def _filter_corpus(source_filter=None, type_filter=None):
    docs = _all_docs()
    if source_filter:
        docs = [d for d in docs if d.metadata.get("source") == source_filter]
    if type_filter:
        docs = [d for d in docs if d.metadata.get("type") == type_filter]
    return docs


def _compose_filter(source_filter=None, type_filter=None):
    clauses = []
    if source_filter:
        clauses.append({"source": source_filter})
    if type_filter:
        clauses.append({"type": type_filter})
    if not clauses:
        return None
    if len(clauses) == 1:
        return clauses[0]
    return {"$and": clauses}


def _vector_retriever(k, source_filter=None, type_filter=None):
    search_kwargs = {
        "k": k,
        "fetch_k": max(config.MMR_FETCH_K, k * 3),
        "lambda_mult": config.MMR_LAMBDA,
    }
    flt = _compose_filter(source_filter, type_filter)
    if flt:
        search_kwargs["filter"] = flt
    return _build_vectorstore().as_retriever(search_type="mmr", search_kwargs=search_kwargs)


def _bm25_tokenize(text):
    """Lowercase + word-character tokenization. Default BM25 splits on whitespace
    only, which makes 'apex' fail to match 'Apex' or 'Apex,'."""
    return re.findall(r"[a-z0-9]+", text.lower())


def _hybrid_retrieve(question, k, source_filter=None, type_filter=None):
    """BM25 + vector ensemble with reciprocal rank fusion (LangChain EnsembleRetriever)."""
    vec = _vector_retriever(k=k, source_filter=source_filter, type_filter=type_filter)
    bm25_corpus = _filter_corpus(source_filter=source_filter, type_filter=type_filter)
    if not bm25_corpus:
        return vec.invoke(question)
    bm25 = BM25Retriever.from_documents(bm25_corpus, preprocess_func=_bm25_tokenize)
    bm25.k = k
    bm25_w = config.HYBRID_BM25_WEIGHT
    ensemble = EnsembleRetriever(
        retrievers=[bm25, vec],
        weights=[bm25_w, 1.0 - bm25_w],
    )
    return ensemble.invoke(question)


def get_retriever(source_filter=None, type_filter=None):
    """Back-compat single retriever (vector only — used by app.py's cache).

    Real querying goes through `retrieve()` which uses the hybrid path.
    """
    return _vector_retriever(k=config.TOP_K,
                             source_filter=source_filter, type_filter=type_filter)


# --- author detection -------------------------------------------------------

def _author_index():
    """Map lowercase name token -> filename, for both first and last names."""
    index = {}
    for path in sorted(config.DATA_DIR.glob("*.pdf")):
        author = author_from_filename(path.name)
        for token in author.split():
            if len(token) >= 3:
                index.setdefault(token.lower(), set()).add(path.name)
    return index


_AUTHOR_INDEX = None


def detect_source_filter(question):
    """Return a filename if the question clearly references one author, else None."""
    global _AUTHOR_INDEX
    if _AUTHOR_INDEX is None:
        _AUTHOR_INDEX = _author_index()
    tokens = re.findall(r"[A-Za-z]+", question.lower())
    matched = set()
    for t in tokens:
        if t in _AUTHOR_INDEX:
            matched |= _AUTHOR_INDEX[t]
    return next(iter(matched)) if len(matched) == 1 else None


# --- numeric-intent detection ----------------------------------------------

_NUMERIC_KEYWORDS = {
    "revenue", "profit", "loss", "income", "expense", "expenses", "cost", "costs",
    "ebitda", "ebit", "margin", "tax", "asset", "assets", "liability", "liabilities",
    "equity", "cash", "debt", "balance", "sheet", "total", "subtotal", "amount",
    "amounts", "value", "values", "price", "prices", "ratio", "ratios", "percent",
    "percentage", "growth", "yoy", "quarter", "fy", "year", "annual",
    "how", "much", "many", "number", "count",
}


def is_numeric_question(question):
    q = question.lower()
    tokens = set(re.findall(r"[a-z]+", q))
    if tokens & _NUMERIC_KEYWORDS:
        return True
    if re.search(r"\$|₹|€|£|\bfy\d{2,4}\b|\b(19|20)\d{2}\b|\d[\d,]*\.?\d*", q):
        return True
    return False


_FIGURE_KEYWORDS = {
    "figure", "figures", "diagram", "diagrams", "chart", "charts", "image",
    "images", "screenshot", "screenshots", "depict", "depicts", "show", "shows",
    "architecture", "flow", "flowchart", "schema", "schematic",
}


def is_figure_question(question):
    return bool(set(re.findall(r"[a-z]+", question.lower())) & _FIGURE_KEYWORDS)


# --- context formatting -----------------------------------------------------

def format_context(docs):
    parts = []
    for i, d in enumerate(docs, 1):
        src = d.metadata.get("source", "?")
        page = d.metadata.get("page", "?")
        kind = d.metadata.get("type", "text")
        tag = {"table": "TABLE", "figure": "FIGURE"}.get(kind, "TEXT")
        body = d.page_content
        if kind == "figure":
            # Framed so the LLM treats granite's output as authoritative content,
            # not as a meta-description to be discounted.
            body = (
                "(This [FIGURE] chunk is the AUTHORITATIVE TRANSCRIPTION of a figure "
                "from the PDF, produced by a vision model. When the user asks about "
                "this figure, draw your answer directly from the text below; do NOT "
                "say the figure is missing or only described.)\n\n" + body
            )
        parts.append(f"[{i}] ({src} p.{page}) [{tag}]\n{body}")
    return "\n\n".join(parts)


def _dedupe(docs):
    seen = set()
    out = []
    for d in docs:
        key = (d.metadata.get("source"), d.metadata.get("page"),
               d.metadata.get("type"), d.page_content[:80])
        if key in seen:
            continue
        seen.add(key)
        out.append(d)
    return out


# --- main entry -------------------------------------------------------------

def retrieve(question, source_filter=None):
    """Hybrid (BM25 + vector) retrieval with type bias for numeric/figure questions."""
    numeric = is_numeric_question(question)
    figure = is_figure_question(question)

    bonus = []
    if numeric:
        k_table = max(1, config.TOP_K // 2)
        bonus += _hybrid_retrieve(question, k=k_table,
                                  source_filter=source_filter,
                                  type_filter="table")
    if figure:
        k_fig = max(1, config.TOP_K // 2)
        bonus += _hybrid_retrieve(question, k=k_fig,
                                  source_filter=source_filter,
                                  type_filter="figure")

    base = _hybrid_retrieve(question, k=config.TOP_K, source_filter=source_filter)
    # Put bonus chunks FIRST so the LLM sees them at the top of the context window.
    docs = _dedupe(bonus + base)[:config.TOP_K + len(bonus)]
    return docs, numeric


def ask(question, llm=None):
    source_filter = detect_source_filter(question)
    docs, numeric = retrieve(question, source_filter=source_filter)
    llm = llm or ChatOllama(model=config.LLM_MODEL, base_url=config.OLLAMA_BASE_URL, temperature=0)
    context = format_context(docs)
    chain = PROMPT | llm | StrOutputParser()
    answer = chain.invoke({"context": context, "question": question})
    return {
        "answer": answer,
        "sources": docs,
        "filtered_to": source_filter,
        "numeric": numeric,
    }


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python query.py \"your question\"")
        sys.exit(1)
    q = " ".join(sys.argv[1:])
    result = ask(q)
    flags = []
    if result["filtered_to"]:
        flags.append(f"filtered to: {result['filtered_to']}")
    if result["numeric"]:
        flags.append("numeric intent → table-biased retrieval")
    if flags:
        print("[" + " | ".join(flags) + "]")
    print("\n=== Answer ===\n")
    print(result["answer"])
    print("\n=== Sources ===")
    for i, d in enumerate(result["sources"], 1):
        kind = d.metadata.get("type", "text")
        print(f"  [{i}] {d.metadata.get('source')} p.{d.metadata.get('page')} [{kind}]")
