"""RAG query: retrieve from Chroma, answer with Ollama llama3.1.

Phase 2 retrieval:
  - Author-name → source filter (Phase 1, unchanged).
  - Numeric-intent detection → dual retrieval that guarantees table chunks
    appear alongside narrative chunks.
  - Prompt instructs the LLM to cite inline as [source p.N].
"""

import re
import sys
from langchain_ollama import ChatOllama
from langchain_core.documents import Document
from langchain_core.messages import AIMessage, HumanMessage
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_core.output_parsers import StrOutputParser
from langchain_community.retrievers import BM25Retriever
from langchain_classic.retrievers.ensemble import EnsembleRetriever

import config
from ingest import author_from_filename
from embeddings import make_vectorstore


SYSTEM_PROMPT = """You are a document-grounded assistant. The user owns and has provided the documents below; you must use them to answer.

Each chunk is tagged with its type:
- [TEXT]   = page text content
- [TABLE]  = a structured table from the PDF (Markdown)
- [FIGURE] = a description of an image/diagram/chart from the PDF, generated by a vision model. The figure text starts with "Figure description:" — TREAT THIS AS THE FIGURE ITSELF. When asked to describe or explain a figure or diagram, use these chunks directly; do not say "I can't see the image."

Rules:
- The context below is the authoritative source. Do not refuse to answer on privacy, confidentiality, or "private company" grounds — every document in the context has been explicitly shared by the user.
- Earlier turns in this conversation may give context for follow-up questions (e.g. "and his revenue?" refers to whoever was discussed previously). Use the chat history to resolve such references, but ALL facts must come from the Context block.
- ATTRIBUTION IS CRITICAL. Every chunk header explicitly states `Document: <filename>` and `Author: <name>`. When you attribute a fact to a person, the chunk you draw it from MUST have that person's name in its Author header. Never say "X's project does Y" using a chunk whose Author is someone else.
- For comparison questions ("how is X's project different from Y's?"), keep facts about X and facts about Y strictly separate based on each chunk's Author header.
- Answer thoroughly with bullet points or short paragraphs.
- Cite every concrete fact inline as [filename p.N] using the headers shown above each chunk.
- When quoting numbers from a table, reproduce the relevant row(s) verbatim and cite the page.
- NUMBER FORMAT: these documents use Indian digit grouping where a space separates groups (e.g. "13 62" means 1362, "9 83" means 983, "(25 42)" means -2542, "1 05" means 105). Read such tokens as single numbers. Parentheses mean negative.
- In YOUR answer, always render numbers in clean standard form with comma separators and currency/unit, e.g. write "₹1,362 lakh" or "₹983 lakh" — NEVER reproduce the raw spaced form like "13 62" or "9 83" in your output.
- When a statement provides a LABELED TOTAL or SUBTOTAL (e.g. "Net Cash Flow from Operating Activities", "Profit for the Year"), quote that stated value directly. Do NOT recompute totals by summing line items.
- NEVER estimate, approximate, or guess a figure. If a specific number (e.g. standalone net profit) is not present in the Context, say it is not available — do not derive it with "≈" or "roughly". A wrong number is worse than "not found".
- Pay attention to each chunk's `Section:` label (e.g. "Standalone Statement of Profit and Loss" vs "Consolidated..."). Attribute every figure to the correct statement based on that label.
- When describing a figure, synthesise from the [FIGURE] chunk's content; quote specific labels/components it lists.
- If the context truly lacks the answer, say so clearly and state what is missing. Do not invent numbers, names, dates, or figure contents.

Context:
{context}"""

PROMPT = ChatPromptTemplate.from_messages([
    ("system", SYSTEM_PROMPT),
    MessagesPlaceholder("history"),
    ("human", "{question}"),
])


REWRITE_SYSTEM = """You rewrite a user's follow-up question into a standalone search query.

Rules:
- Resolve pronouns and references using the chat history ("his", "it", "that one", "the second").
- Preserve the original intent and keywords.
- Output ONLY the rewritten query — no preamble, no explanation, no quotes.
- If the question is already standalone, output it unchanged.

Examples:
History: "what is riyansh's project about" -> "Riyansh built a real-time market data backend"
Follow-up: "and his revenue?"
Rewrite: what is riyansh sachdev's revenue from the project

Follow-up: "summarize it"
History: "describe vikhyat's methodology" -> "Vikhyat used the TRIGRS model..."
Rewrite: summarize vikhyat's methodology"""

REWRITE_PROMPT = ChatPromptTemplate.from_messages([
    ("system", REWRITE_SYSTEM),
    MessagesPlaceholder("history"),
    ("human", "Rewrite this follow-up as a standalone query: {question}"),
])


# --- vectorstore + retriever ------------------------------------------------

_VECTORSTORE = None
_CORPUS = None  # list[Document] of all chunks, for BM25


def _build_vectorstore():
    global _VECTORSTORE
    if _VECTORSTORE is None:
        _VECTORSTORE = make_vectorstore()
    return _VECTORSTORE


def _all_docs():
    """Load every chunk from Chroma into memory once; reused for BM25."""
    global _CORPUS
    if _CORPUS is None:
        vs = _build_vectorstore()
        res = vs.get()
        _CORPUS = [
            Document(page_content=d, metadata=m or {})
            for d, m in zip(res["documents"], res["metadatas"])
        ]
    return _CORPUS


def _filter_corpus(source_filter=None, type_filter=None):
    docs = _all_docs()
    if source_filter:
        docs = [d for d in docs if d.metadata.get("source") == source_filter]
    if type_filter:
        docs = [d for d in docs if d.metadata.get("type") == type_filter]
    return docs


def _compose_filter(source_filter=None, type_filter=None):
    clauses = []
    if source_filter:
        clauses.append({"source": source_filter})
    if type_filter:
        clauses.append({"type": type_filter})
    if not clauses:
        return None
    if len(clauses) == 1:
        return clauses[0]
    return {"$and": clauses}


def _vector_retriever(k, source_filter=None, type_filter=None):
    search_kwargs = {
        "k": k,
        "fetch_k": max(config.MMR_FETCH_K, k * 3),
        "lambda_mult": config.MMR_LAMBDA,
    }
    flt = _compose_filter(source_filter, type_filter)
    if flt:
        search_kwargs["filter"] = flt
    return _build_vectorstore().as_retriever(search_type="mmr", search_kwargs=search_kwargs)


def _bm25_tokenize(text):
    """Lowercase + word-character tokenization. Default BM25 splits on whitespace
    only, which makes 'apex' fail to match 'Apex' or 'Apex,'."""
    return re.findall(r"[a-z0-9]+", text.lower())


def _hybrid_retrieve(question, k, source_filter=None, type_filter=None):
    """BM25 + vector ensemble with reciprocal rank fusion (LangChain EnsembleRetriever)."""
    vec = _vector_retriever(k=k, source_filter=source_filter, type_filter=type_filter)
    bm25_corpus = _filter_corpus(source_filter=source_filter, type_filter=type_filter)
    if not bm25_corpus:
        return vec.invoke(question)
    bm25 = BM25Retriever.from_documents(bm25_corpus, preprocess_func=_bm25_tokenize)
    bm25.k = k
    bm25_w = config.HYBRID_BM25_WEIGHT
    ensemble = EnsembleRetriever(
        retrievers=[bm25, vec],
        weights=[bm25_w, 1.0 - bm25_w],
    )
    return ensemble.invoke(question)


def get_retriever(source_filter=None, type_filter=None):
    """Back-compat single retriever (vector only — used by app.py's cache).

    Real querying goes through `retrieve()` which uses the hybrid path.
    """
    return _vector_retriever(k=config.TOP_K,
                             source_filter=source_filter, type_filter=type_filter)


# --- author detection -------------------------------------------------------

def _author_index():
    """Map lowercase name token -> filename, for both first and last names."""
    index = {}
    for path in sorted(config.DATA_DIR.glob("*.pdf")):
        author = author_from_filename(path.name)
        for token in author.split():
            if len(token) >= 3:
                index.setdefault(token.lower(), set()).add(path.name)
    return index


def _author_by_filename():
    """filename -> author display name."""
    return {p.name: author_from_filename(p.name)
            for p in sorted(config.DATA_DIR.glob("*.pdf"))}


_AUTHOR_INDEX = None
_AUTHOR_INDEX_BY_FILENAME = _author_by_filename()


def detect_all_sources(*questions):
    """Return the set of filenames matched by any of the provided question strings.
    Pass both the original and rewritten query so rewriter-induced spelling drift
    (e.g. 'Sanjna' → 'sanjana') doesn't drop a real match."""
    global _AUTHOR_INDEX
    if _AUTHOR_INDEX is None:
        _AUTHOR_INDEX = _author_index()
    matched = set()
    for q in questions:
        if not q:
            continue
        for t in re.findall(r"[A-Za-z]+", q.lower()):
            if t in _AUTHOR_INDEX:
                matched |= _AUTHOR_INDEX[t]
    return matched


def detect_source_filter(question, *extra_questions):
    """Return a single filename when the question(s) reference exactly one author,
    else None. Multi-question form lets the caller include the rewritten query."""
    matched = detect_all_sources(question, *extra_questions)
    return next(iter(matched)) if len(matched) == 1 else None


# --- numeric-intent detection ----------------------------------------------

_NUMERIC_KEYWORDS = {
    "revenue", "profit", "loss", "income", "expense", "expenses", "cost", "costs",
    "ebitda", "ebit", "margin", "tax", "asset", "assets", "liability", "liabilities",
    "equity", "cash", "debt", "balance", "sheet", "total", "subtotal", "amount",
    "amounts", "value", "values", "price", "prices", "ratio", "ratios", "percent",
    "percentage", "growth", "yoy", "quarter", "fy", "year", "annual",
    "how", "much", "many", "number", "count",
}


def is_numeric_question(question):
    q = question.lower()
    tokens = set(re.findall(r"[a-z]+", q))
    if tokens & _NUMERIC_KEYWORDS:
        return True
    if re.search(r"\$|₹|€|£|\bfy\d{2,4}\b|\b(19|20)\d{2}\b|\d[\d,]*\.?\d*", q):
        return True
    return False


_FIGURE_KEYWORDS = {
    "figure", "figures", "diagram", "diagrams", "chart", "charts", "image",
    "images", "screenshot", "screenshots", "depict", "depicts", "show", "shows",
    "architecture", "flow", "flowchart", "schema", "schematic",
}


def is_figure_question(question):
    return bool(set(re.findall(r"[a-z]+", question.lower())) & _FIGURE_KEYWORDS)


# --- financial-statement intent --------------------------------------------

# Map query phrases -> the statement-title keyword to look for in `section` meta.
_STATEMENT_INTENTS = {
    "profit and loss": ["profit and loss", "profit & loss", "net profit",
                        "profit for the year", "income statement", "p&l", "revenue",
                        "total income", "earnings"],
    "balance sheet": ["balance sheet", "total assets", "total equity",
                      "liabilities", "net worth"],
    "cash flow": ["cash flow", "operating activities", "investing activities",
                 "financing activities"],
    "changes in equity": ["changes in equity"],
}

_VARIANTS = ["standalone", "consolidated"]


def detect_statement_targets(question):
    """Return list of (variant_or_None, statement_keyword) the question implies.
    e.g. 'standalone vs consolidated net profit' -> [('standalone','profit and loss'),
    ('consolidated','profit and loss')]."""
    q = question.lower()
    statements = [stmt for stmt, kws in _STATEMENT_INTENTS.items()
                  if any(kw in q for kw in kws)]
    if not statements:
        return []
    variants = [v for v in _VARIANTS if v in q]
    targets = []
    for stmt in statements:
        if variants:
            for v in variants:
                targets.append((v, stmt))
        else:
            targets.append((None, stmt))
    return targets


def _doc_matches_statement(doc, variant, statement):
    """Match a chunk to a (variant, statement) target. Table chunks carry a
    `section` label; text chunks embed the statement title in their content, so
    check both. Table extraction sometimes drops rows (e.g. 'Profit for the
    Year'), so the complete text chunk is often the more reliable source."""
    section = (doc.metadata.get("section") or "").lower()
    # First ~300 chars of content usually holds the statement title line.
    head = doc.page_content[:300].lower()
    hay = section + " " + head
    if statement not in hay:
        return False
    if variant and variant not in hay:
        return False
    return True


# --- context formatting -----------------------------------------------------

def format_context(docs):
    parts = []
    for i, d in enumerate(docs, 1):
        src = d.metadata.get("source", "?")
        page = d.metadata.get("page", "?")
        kind = d.metadata.get("type", "text")
        tag = {"table": "TABLE", "figure": "FIGURE"}.get(kind, "TEXT")
        body = d.page_content
        if kind == "figure":
            # Framed so the LLM treats granite's output as authoritative content,
            # not as a meta-description to be discounted.
            body = (
                "(This [FIGURE] chunk is the AUTHORITATIVE TRANSCRIPTION of a figure "
                "from the PDF, produced by a vision model. When the user asks about "
                "this figure, draw your answer directly from the text below; do NOT "
                "say the figure is missing or only described.)\n\n" + body
            )
        parts.append(f"[{i}] ({src} p.{page}) [{tag}]\n{body}")
    return "\n\n".join(parts)


def _dedupe(docs):
    seen = set()
    out = []
    for d in docs:
        key = (d.metadata.get("source"), d.metadata.get("page"),
               d.metadata.get("type"), d.page_content[:80])
        if key in seen:
            continue
        seen.add(key)
        out.append(d)
    return out


# --- main entry -------------------------------------------------------------

def retrieve(question, source_filter=None, multi_sources=None):
    """Hybrid (BM25 + vector) retrieval with type / multi-source biasing.

    multi_sources: iterable of filenames. When set, retrieval is RESTRICTED to
        those sources (no corpus-wide fallback) so unrelated authors can't
        leak into the comparison context.
    """
    numeric = is_numeric_question(question)
    figure = is_figure_question(question)

    if multi_sources and not source_filter:
        # Multi-author comparison: per-source pull only, equal seats each.
        # We retrieve TWO query variants per source:
        #   1. The literal comparison query (catches direct hits)
        #   2. A synthetic "describe this project" probe per author, scoped to
        #      that source — guarantees foundational intro/abstract chunks land
        #      in context so the LLM can actually describe each project.
        docs = []
        k_per = max(3, config.TOP_K // len(multi_sources) + 2)
        for src in multi_sources:
            author = _AUTHOR_INDEX_BY_FILENAME.get(src, "")
            probe = (f"what is {author}'s project about, its scope, technologies, "
                     f"and key outcomes") if author else \
                    f"what is this project about, its scope, technologies, outcomes"
            docs += _hybrid_retrieve(question, k=k_per, source_filter=src)
            docs += _hybrid_retrieve(probe, k=k_per, source_filter=src)
            if numeric:
                docs += _hybrid_retrieve(question, k=max(2, k_per // 2),
                                         source_filter=src, type_filter="table")
            if figure:
                docs += _hybrid_retrieve(question, k=max(2, k_per // 2),
                                         source_filter=src, type_filter="figure")
        return _dedupe(docs), numeric

    # Single-source or unfiltered path. Ordered by priority — most important
    # bonus first, because the total is capped at MAX_CONTEXT_CHUNKS.

    # 1. Statement-targeted (highest priority): for each (variant, statement)
    #    the question implies, find the statement's page(s) and pull EVERY chunk
    #    from them. Table extraction can drop rows (e.g. 'Profit for the Year'),
    #    and the title vs the figure often land in different sub-chunks, so the
    #    whole page is needed to guarantee complete, correctly-labelled figures.
    statement_bonus = []
    for variant, statement in detect_statement_targets(question):
        probe = f"{variant or ''} {statement}".strip()
        cand = _hybrid_retrieve(probe, k=config.TOP_K * 2, source_filter=source_filter)
        target_pages = {(d.metadata.get("source"), d.metadata.get("page"))
                        for d in cand if _doc_matches_statement(d, variant, statement)}
        for src, pg in target_pages:
            statement_bonus += [d for d in _all_docs()
                                if d.metadata.get("source") == src
                                and d.metadata.get("page") == pg]

    # 2. Type bias.
    type_bonus = []
    if numeric:
        type_bonus += _hybrid_retrieve(question, k=max(1, config.TOP_K // 2),
                                       source_filter=source_filter, type_filter="table")
    if figure:
        type_bonus += _hybrid_retrieve(question, k=max(1, config.TOP_K // 2),
                                       source_filter=source_filter, type_filter="figure")

    # 3. General hybrid base.
    base = _hybrid_retrieve(question, k=config.TOP_K, source_filter=source_filter)

    docs = _dedupe(statement_bonus + type_bonus + base)[:config.MAX_CONTEXT_CHUNKS]
    return docs, numeric


def _history_to_messages(history):
    """Convert [{'role': 'user'|'assistant', 'content': str}, ...] to LC messages.
    Trims to the last HISTORY_TURNS entries."""
    if not history:
        return []
    window = history[-config.HISTORY_TURNS:]
    msgs = []
    for turn in window:
        role = turn.get("role")
        content = turn.get("content", "")
        if role == "user":
            msgs.append(HumanMessage(content=content))
        elif role == "assistant":
            msgs.append(AIMessage(content=content))
    return msgs


def rewrite_query(question, history, llm=None):
    """Rewrite a follow-up into a standalone search query. Returns the question
    unchanged if history is empty (saves a model call on first turn)."""
    if not history:
        return question
    llm = llm or ChatOllama(model=config.LLM_MODEL, base_url=config.OLLAMA_BASE_URL, temperature=0)
    chain = REWRITE_PROMPT | llm | StrOutputParser()
    rewritten = chain.invoke({
        "history": _history_to_messages(history),
        "question": question,
    }).strip().strip('"').strip("'")
    return rewritten or question


def ask(question, history=None, llm=None):
    """Run one RAG turn.

    Args:
        question: the user's raw input.
        history: optional list of prior turns [{"role": ..., "content": ...}, ...].
        llm: optional pre-built ChatOllama (used for tests/reuse).

    Returns dict with answer, sources, filter, numeric flag, and rewritten_query.
    """
    history = history or []
    llm = llm or ChatOllama(model=config.LLM_MODEL, base_url=config.OLLAMA_BASE_URL, temperature=0)

    rewritten = rewrite_query(question, history, llm=llm)
    # Run filter detection over BOTH the original and the rewritten query so
    # rewriter-induced spelling drift doesn't lose a real author match.
    all_sources = detect_all_sources(question, rewritten)
    source_filter = next(iter(all_sources)) if len(all_sources) == 1 else None
    multi_sources = all_sources if len(all_sources) >= 2 else None
    docs, numeric = retrieve(rewritten, source_filter=source_filter,
                             multi_sources=multi_sources)
    context = format_context(docs)

    chain = PROMPT | llm | StrOutputParser()
    answer = chain.invoke({
        "context": context,
        "history": _history_to_messages(history),
        "question": question,  # original — keeps tone natural
    })
    return {
        "answer": answer,
        "sources": docs,
        "filtered_to": source_filter,
        "multi_sources": sorted(multi_sources) if multi_sources else None,
        "numeric": numeric,
        "rewritten_query": rewritten if rewritten != question else None,
    }


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python query.py \"your question\"")
        sys.exit(1)
    q = " ".join(sys.argv[1:])
    result = ask(q)
    flags = []
    if result["filtered_to"]:
        flags.append(f"filtered to: {result['filtered_to']}")
    if result["numeric"]:
        flags.append("numeric intent → table-biased retrieval")
    if result.get("rewritten_query"):
        flags.append(f"rewritten: {result['rewritten_query']}")
    if flags:
        print("[" + " | ".join(flags) + "]")
    print("\n=== Answer ===\n")
    print(result["answer"])
    print("\n=== Sources ===")
    for i, d in enumerate(result["sources"], 1):
        kind = d.metadata.get("type", "text")
        print(f"  [{i}] {d.metadata.get('source')} p.{d.metadata.get('page')} [{kind}]")
