# Generated by Django 6.0.5 on 2026-06-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='mode',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
