# Generated by Django 6.0.5 on 2026-06-02 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.JSONField(default=dict)),
                ('mode', models.CharField(max_length=20)),
                ('body_md', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_note', to='chat.message')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FactProvenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(db_index=True, max_length=64)),
                ('period', models.CharField(db_index=True, max_length=16)),
                ('metric_key', models.CharField(max_length=64)),
                ('value', models.DecimalField(decimal_places=4, max_digits=20)),
                ('unit', models.CharField(max_length=16)),
                ('statement_variant', models.CharField(blank=True, default='', max_length=16)),
                ('source_doc', models.CharField(blank=True, default='', max_length=255)),
                ('source_page', models.IntegerField(blank=True, null=True)),
                ('confidence', models.FloatField(default=1.0)),
                ('operation', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extracted_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provenance_entries', to='chat.message')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'period', 'metric_key', '-created_at'], name='chat_factpr_company_c6fd2c_idx')],
            },
        ),
        migrations.CreateModel(
            name='MetricFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(db_index=True, max_length=64)),
                ('period', models.CharField(db_index=True, max_length=16)),
                ('metric_key', models.CharField(db_index=True, max_length=64)),
                ('value', models.DecimalField(decimal_places=4, max_digits=20)),
                ('unit', models.CharField(choices=[('inr_crore', 'INR crore'), ('inr_lakh', 'INR lakh'), ('inr', 'INR (absolute)'), ('usd_million', 'USD million'), ('usd', 'USD (absolute)'), ('pct', 'Percentage'), ('rupees', 'Rupees per share'), ('count', 'Count'), ('ratio', 'Ratio (x)'), ('days', 'Days')], max_length=16)),
                ('statement_variant', models.CharField(blank=True, choices=[('', 'Unspecified'), ('standalone', 'Standalone'), ('consolidated', 'Consolidated')], default='', max_length=16)),
                ('source_doc', models.CharField(blank=True, default='', max_length=255)),
                ('source_page', models.IntegerField(blank=True, null=True)),
                ('confidence', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extracted_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracted_facts', to='chat.message')),
            ],
            options={
                'ordering': ['company', 'period', 'metric_key'],
                'indexes': [models.Index(fields=['company', 'period'], name='chat_metric_company_448817_idx'), models.Index(fields=['company', 'metric_key'], name='chat_metric_company_a99c5e_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'period', 'metric_key', 'statement_variant', 'unit'), name='uniq_metric_fact')],
            },
        ),
    ]
