# Generated by Django 6.0.5 on 2026-06-03 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_analysisnote_factprovenance_metricfact'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('stored_path', models.CharField(blank=True, default='', max_length=512)),
                ('pages', models.IntegerField(default=0)),
                ('chunk_count', models.IntegerField(default=0)),
                ('collection_name', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('indexing', 'Indexing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='chat.chat')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('chat', 'sha256'), name='uniq_chat_upload_sha')],
            },
        ),
    ]
